/**
 * CMS Data Loader - Populates static HTML with data from JSON files.
 * Expects data/products.json, data/companies.json, etc. (generated by npm run build:data)
 */
(function () {
  'use strict';

  async function fetchJSON(path) {
    const base = window.location.pathname.replace(/\/[^/]*$/, '') || '';
    const url = (base.endsWith('/') ? base : base + '/') + 'data/' + path;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to load ${path}`);
    return res.json();
  }

  function getPageType() {
    const path = window.location.pathname;
    if (path.endsWith('index.html') || path === '/' || path.endsWith('/')) return 'index';
    if (path.includes('products')) return path.includes('detail_') ? 'detail_product' : 'products';
    if (path.includes('companies')) return path.includes('detail_') ? 'detail_company' : 'companies';
    if (path.includes('patents')) return path.includes('detail_') ? 'detail_patent' : 'patents';
    if (path.includes('skills')) return path.includes('detail_') ? 'detail_skill' : 'skills';
    return null;
  }

  function getSlug() {
    const params = new URLSearchParams(window.location.search);
    return params.get('slug') || params.get('item');
  }

  function formatDate(str) {
    if (!str) return '';
    const m = str.match(/(\w{3})\s+(\d{1,2}),?\s+(\d{4})/);
    if (m) return `${m[1]} ${m[2]}, ${m[3]}`;
    return str;
  }

  function parseDateForSort(str) {
    if (!str) return 0;
    const d = new Date(str);
    return isNaN(d.getTime()) ? 0 : d.getTime();
  }

  /** Items in progress with no end date sort first (top). getEndDate(item) returns the end date; inProgress(item) returns true to force top. */
  function sortValueForEndDate(item, getEndDate, inProgress) {
    const endDate = getEndDate(item);
    if (inProgress && inProgress(item)) return Number.MAX_SAFE_INTEGER; /* tiebreak: use start date */
    return parseDateForSort(endDate);
  }

  function setText(el, text) {
    if (el) {
      el.textContent = text || '';
      el.classList.remove('w-dyn-bind-empty');
    }
  }

  function setHtml(el, html) {
    if (el) {
      el.innerHTML = html || '';
      el.classList.remove('w-dyn-bind-empty');
    }
  }

  function setAttr(el, attr, val) {
    if (el && val) el.setAttribute(attr, val);
  }

  function setImgSrc(img, src) {
    if (img && src) {
      img.src = src;
      img.style.display = '';
      img.classList.remove('w-dyn-bind-empty');
    }
  }

  // --- INDEX PAGE ---
  async function renderIndex(data) {
    const { products, companies, skills } = data;

    const featuredProducts = products
      .filter(p => p.Featured === 'true')
      .sort((a, b) => (a['Sort Order'] || 999) - (b['Sort Order'] || 999))
      .slice(0, 6);
    const companiesMap = Object.fromEntries(companies.map(c => [c.Slug, c]));
    const skillsMap = Object.fromEntries(skills.map(s => [s.Slug, s]));

    // Companies (logos) - first company logo block
    const logoItems = document.querySelectorAll('.logo-wrapper.w-dyn-item');
    if (logoItems.length && companies.length) {
      const list = logoItems[0].closest('.w-dyn-items');
      const template = logoItems[0].cloneNode(true);
      if (list) {
        list.innerHTML = '';
        list.closest('.w-dyn-list')?.querySelector('.w-dyn-empty')?.style.setProperty('display', 'none');
        companies.forEach(c => {
          const clone = template.cloneNode(true);
          const link = clone.querySelector('a.logo-link-block, a[id*="company"]');
          const imgs = clone.querySelectorAll('img.logo');
          if (link) link.href = `companies.html?slug=${c.Slug}`;
          const logoBlue = c['Logo (blue)'] || c.Thumbnail;
          const logoWhite = c['Logo (White)'] || c.Thumbnail;
          setImgSrc(imgs[0], logoWhite);
          setImgSrc(imgs[1], logoBlue);
          list.appendChild(clone);
        });
      }
    }

    // Featured products (portfolio list)
    const portfolioItems = document.querySelectorAll('.portfolio-list .w-dyn-item');
    if (portfolioItems.length && featuredProducts.length) {
      const list = portfolioItems[0].closest('.w-dyn-items');
      const template = portfolioItems[0].cloneNode(true);
      if (list) {
        list.innerHTML = '';
        list.closest('.w-dyn-list')?.querySelector('.w-dyn-empty')?.style.setProperty('display', 'none');
        featuredProducts.forEach(p => {
          const clone = template.cloneNode(true);
          const detailUrl = `detail_products.html?slug=${p.Slug}`;
          clone.querySelectorAll('a.portfolio-image-link, a[id*="view-project"]').forEach(a => { a.href = detailUrl; });
          setImgSrc(clone.querySelector('.portfolio-image'), p['Thumbnai Image'] || p['Project Image']);
          const overlay = clone.querySelector('.image-overlay');
          if (overlay) overlay.style.transform = 'translate3d(0, 100%, 0)';
          const company = companies.find(c => c.Slug === p['Startup Company']);
          setText(clone.querySelector('.heading-style-h5'), p.Name);
          setText(clone.querySelector('.heading-style-h6'), p['50 Character Description']);
          setText(clone.querySelector('.text-size-regular.dark'), p.Summary);
          const tagList = clone.querySelector('.portfolio-tag-list');
          if (tagList) {
            const tagTemplate = tagList.querySelector('.w-dyn-item');
            const skillSlugs = p.Skills || [];
            if (tagTemplate && skillSlugs.length) {
              const tagTemplateCopy = tagTemplate.cloneNode(true);
              tagList.innerHTML = '';
              skillSlugs.forEach(slug => {
                const tagClone = tagTemplateCopy.cloneNode(true);
                const skill = skillsMap[slug];
                setText(tagClone.querySelector('.portfolio-tag-item .tag-text'), skill?.Name || slug);
                tagList.appendChild(tagClone);
              });
            }
          }
          list.appendChild(clone);
        });
      }
    }

    // Skills
    const skillItems = document.querySelectorAll('.service-component .service-item');
    if (skillItems.length && skills.length) {
      const wrapper = skillItems[0].closest('.w-dyn-item');
      const list = wrapper?.closest('.w-dyn-items');
      const template = wrapper?.cloneNode(true);
      if (list && template) {
        list.innerHTML = '';
        list.closest('.w-dyn-list')?.querySelector('.w-dyn-empty')?.style.setProperty('display', 'none');
        skills.forEach(s => {
          const clone = template.cloneNode(true);
          setText(clone.querySelector('.text-size-medium.text-color-white'), s.Name);
          setText(clone.querySelector('p.w-dyn-bind-empty'), s.Description);
          list.appendChild(clone);
        });
      }
    }
  }

  // --- PRODUCTS LIST PAGE ---
  async function renderProductsList(products) {
    const items = document.querySelectorAll('.work-item');
    if (!items.length) return;
    const wrapper = items[0].closest('.w-dyn-item');
    const list = wrapper?.closest('.w-dyn-items');
    if (!list) return;

    const prodInProgress = p => p['In Progress'] === 'true' && !p['End Date'];
    const sorted = [...products].sort((a, b) => sortValueForEndDate(b, p => p['End Date'], prodInProgress) - sortValueForEndDate(a, p => p['End Date'], prodInProgress));
    const template = wrapper.cloneNode(true);
    list.innerHTML = '';
    list.closest('.w-dyn-list')?.querySelector('.w-dyn-empty')?.style.setProperty('display', 'none');
    sorted.forEach(p => {
      const clone = template.cloneNode(true);
      const workItem = clone.querySelector('.work-item');
      const link = clone.querySelector('a.work-link, a[id*="product"]');
      if (link) link.href = `detail_products.html?slug=${p.Slug}`;
      setText(workItem?.querySelector('.products'), p.Name);
      setText(workItem?.querySelector('.work-heading .text-size-medium'), p['50 Character Description'] || p.Summary);
      const dateEl = workItem?.querySelector('.work-heading + .portfolio-date');
      setText(dateEl, (p['Start Date'] || '') + (p['End Date'] ? ` - ${p['End Date']}` : ''));
      setImgSrc(workItem?.querySelector('.product-list-thumbnail-image'), p['Thumbnai Image'] || p['Project Image']);
      const inProgress = workItem?.querySelectorAll('.portfolio-date')[1];
      if (inProgress && p['In Progress'] === 'true') inProgress.style.display = '';
      else if (inProgress) inProgress.style.display = 'none';
      list.appendChild(clone);
    });
  }

  // --- COMPANIES LIST PAGE ---
  async function renderCompaniesList(companies) {
    const items = document.querySelectorAll('.work-item');
    if (!items.length) return;
    const wrapper = items[0].closest('.w-dyn-item');
    const list = wrapper?.closest('.w-dyn-items');
    if (!list) return;

    const coInProgress = c => !c['End Date'];
    const sorted = [...companies].sort((a, b) => sortValueForEndDate(b, c => c['End Date'], coInProgress) - sortValueForEndDate(a, c => c['End Date'], coInProgress));
    const template = wrapper.cloneNode(true);
    list.innerHTML = '';
    list.closest('.w-dyn-list')?.querySelector('.w-dyn-empty')?.style.setProperty('display', 'none');
    sorted.forEach(c => {
      const clone = template.cloneNode(true);
      const workItem = clone.querySelector('.work-item');
      const link = clone.querySelector('a.work-link, a[id*="product"]');
      if (link) link.href = `detail_companies.html?slug=${c.Slug}`;
      setText(workItem?.querySelector('.products'), c.Name);
      setText(workItem?.querySelector('.work-heading .text-size-medium'), c['50 Character Description']);
      const dateEl = workItem?.querySelector('.work-heading + .portfolio-date');
      setText(dateEl, (c['Start Date'] || '') + (c['End Date'] ? ` - ${c['End Date']}` : ''));
      setImgSrc(workItem?.querySelector('.product-list-thumbnail-image'), c.Thumbnail || c['Hero Image']);
      list.appendChild(clone);
    });
  }

  // --- PATENTS LIST PAGE ---
  async function renderPatentsList(patents) {
    const items = document.querySelectorAll('.work-item');
    if (!items.length) return;
    const wrapper = items[0].closest('.w-dyn-item');
    const list = wrapper?.closest('.w-dyn-items');
    if (!list) return;

    const patentEndDate = p => p['Patented Date'] || p['End Date'];
    const patentInProgress = p => p['In Progress'] === 'true' && !patentEndDate(p);
    const sorted = [...patents].sort((a, b) => sortValueForEndDate(b, patentEndDate, patentInProgress) - sortValueForEndDate(a, patentEndDate, patentInProgress));
    const template = wrapper.cloneNode(true);
    list.innerHTML = '';
    list.closest('.w-dyn-list')?.querySelector('.w-dyn-empty')?.style.setProperty('display', 'none');
    sorted.forEach(p => {
      const clone = template.cloneNode(true);
      const workItem = clone.querySelector('.work-item');
      const link = clone.querySelector('a.work-link, a[id*="product"]');
      if (link) link.href = p['Google Patent URL'] || `detail_patents.html?slug=${p.Slug}`;
      setText(workItem?.querySelector('.products'), p.Name);
      setText(workItem?.querySelector('.work-heading .text-size-medium'), p['50 Character Description'] || p.Summary);
      const dateEl = workItem?.querySelector('.work-heading + .portfolio-date');
      setText(dateEl, p['Patented Date'] || p['End Date'] || '');
      setImgSrc(workItem?.querySelector('.product-list-thumbnail-image'), p['Thumbnai Image'] || p['Project Image']);
      list.appendChild(clone);
    });
  }

  // --- DETAIL PRODUCT PAGE ---
  async function renderDetailProduct(product, companies, productImages, skills = []) {
    const company = companies.find(c => c.Slug === product['Startup Company']);
    const images = (productImages || []).filter(pi => pi.Product === product.Slug);
    const skillsMap = Object.fromEntries((skills || []).map(s => [s.Slug, s]));

    setText(document.querySelector('.portfolio-header-content-left h1'), product.Name);
    setText(document.querySelector('.portfolio-header-content-left h4'), product['50 Character Description'] || product.Summary);
    setText(document.querySelector('.portfolio-header-content-left .text-size-medium'), product.Description || '');
    setImgSrc(document.querySelector('.hero-image'), product['Project Image'] || product['Thumbnai Image']);

    const tagList = document.querySelector('.portfolio-header-tag-list');
    const skillSlugs = product.Skills || [];
    if (tagList && skillSlugs.length) {
      const template = tagList.querySelector('.w-dyn-item');
      if (template) {
        const templateCopy = template.cloneNode(true);
        tagList.innerHTML = '';
        skillSlugs.forEach(slug => {
          const clone = templateCopy.cloneNode(true);
          const skill = skillsMap[slug];
          setText(clone.querySelector('.portfolio-header-tag-item .tag-text'), skill?.Name || slug);
          tagList.appendChild(clone);
        });
      }
    }

    if (company) {
      const logoLink = document.querySelector('#body-company-button');
      if (logoLink) logoLink.href = `detail_companies.html?slug=${company.Slug}`;
      const logos = document.querySelectorAll('.company-logo .logo-3');
      setImgSrc(logos[0], company['Logo (blue)'] || company.Thumbnail);
      setImgSrc(logos[1], company['Logo (White)'] || company.Thumbnail);
    }

    setText(document.querySelector('.text-block.w-dyn-bind-empty'), formatDate(product['Start Date']));
    setText(document.querySelector('.text-block-2.w-dyn-bind-empty'), product['End Date'] ? formatDate(product['End Date']) : 'Present');

    setHtml(document.querySelector('#section-highlights + .w-richtext, .w-dyn-bind-empty.w-richtext'), product.Highlights || '');
    setHtml(document.querySelector('#section-press-release .w-richtext'), product['Press Release'] || '');
    const richTexts = document.querySelectorAll('.text-rich-text.w-richtext');
    if (richTexts.length) setHtml(richTexts[richTexts.length - 1], product['Services Text'] || '');

    // Product images gallery
    if (images.length) {
      const imgTemplate = document.querySelector('.collection-item-2.w-dyn-item');
      const imgList = document.querySelector('.collection-list-3.w-dyn-items');
      if (imgTemplate && imgList) {
        imgList.innerHTML = '';
        images.forEach((pi, i) => {
          const clone = imgTemplate.cloneNode(true);
          const link = clone.querySelector('.product-image-wrapper');
          const img = clone.querySelector('.product-image');
          const desc = clone.querySelector('.product-image-description');
          if (link) {
            link.setAttribute('productname', product.Name);
            link.setAttribute('productimagename', pi.Name);
          }
          setImgSrc(img, pi.Image);
          setText(desc, pi['Image Description']);
          if (i === 0) {
            const enlarged = document.querySelector('.enlarged-product-image');
            if (enlarged) enlarged.src = pi.Image;
            const enlargedDesc = document.querySelector('.product-image-description');
            if (enlargedDesc) enlargedDesc.textContent = pi['Image Description'];
          }
          imgList.appendChild(clone);
        });
      }
    }
  }

  // --- DETAIL COMPANY PAGE ---
  async function renderDetailCompany(company, products, patents) {
    const productSlugs = (company.Products || []).map(s => s.trim());
    const patentSlugs = (company.Patents || []).map(s => s.trim());
    const companyProducts = (products || []).filter(p => productSlugs.includes(p.Slug));
    const companyPatents = (patents || []).filter(p => patentSlugs.includes(p.Slug));

    setText(document.querySelector('.portfolio-header-content-left h1'), company.Name);
    setText(document.querySelector('.portfolio-header-content-left h4'), company['Company Type'] || company.Industry || '');
    setText(document.querySelector('.portfolio-header-content-left .text-size-medium'), company['50 Character Description']);
    setImgSrc(document.querySelector('.hero-image'), company['Hero Image'] || company.Thumbnail);

    const logoLink = document.querySelector('#body-company-logo-button');
    if (logoLink) logoLink.href = company.Website || company['Website Short'] || '#';
    const logos = document.querySelectorAll('.company-logo .logo-3');
    setImgSrc(logos[0], company['Logo (blue)'] || company.Thumbnail);
    setImgSrc(logos[1], company['Logo (White)'] || company.Thumbnail);

    setHtml(document.querySelector('.portfolio-header-content-left + .w-richtext, .w-dyn-bind-empty.w-richtext'), company['Detailed Description'] || company.Highlights || '');

    // Products list in company (first work-component)
    const workComponents = document.querySelectorAll('.work-component');
    if (workComponents.length >= 1 && companyProducts.length) {
      const list = workComponents[0].querySelector('.w-dyn-items');
      const template = list?.querySelector('.w-dyn-item');
      if (template && list) {
        list.innerHTML = '';
        companyProducts.forEach(p => {
          const clone = template.cloneNode(true);
          const workItem = clone.querySelector('.work-item');
          setText(workItem?.querySelector('.products'), p.Name);
          setText(workItem?.querySelector('.text-size-medium'), p['50 Character Description'] || p.Summary);
          setText(workItem?.querySelector('.portfolio-date'), formatDate(p['Start Date']));
          const link = clone.querySelector('a.work-link');
          if (link) link.href = `detail_products.html?slug=${p.Slug}`;
          setImgSrc(workItem?.querySelector('.product-list-thumbnail-image'), p['Thumbnai Image'] || p['Project Image']);
          list.appendChild(clone);
        });
      }
    }
    // Patents list in company (second work-component)
    if (workComponents.length >= 2 && companyPatents.length) {
      const list = workComponents[1].querySelector('.w-dyn-items');
      const template = list?.querySelector('.w-dyn-item');
      if (template && list) {
        list.innerHTML = '';
        companyPatents.forEach(p => {
          const clone = template.cloneNode(true);
          const workItem = clone.querySelector('.work-item');
          setText(workItem?.querySelector('.products'), p.Name);
          setText(workItem?.querySelector('.text-size-medium'), p['50 Character Description'] || p.Summary);
          setText(workItem?.querySelector('.portfolio-date'), formatDate(p['Patented Date']) || formatDate(p['End Date']));
          const link = clone.querySelector('a.work-link');
          if (link) link.href = `detail_patents.html?slug=${p.Slug}`;
          setImgSrc(workItem?.querySelector('.product-list-thumbnail-image'), p['Thumbnai Image'] || p['Project Image']);
          list.appendChild(clone);
        });
      }
    }
  }

  // --- DETAIL PATENT PAGE ---
  async function renderDetailPatent(patent) {
    setText(document.querySelector('.portfolio-header-content-left h1'), patent.Name);
    setText(document.querySelector('.portfolio-header-content-left h4'), patent['Startup Company'] || '');
    setText(document.querySelector('.portfolio-header-content-left .text-size-medium'), patent['50 Character Description'] || patent.Summary);
    setImgSrc(document.querySelector('.hero-image'), patent['Project Image'] || patent['Thumbnai Image']);
    setHtml(document.querySelector('.w-dyn-bind-empty.w-richtext'), patent.Description || patent.Abstract || '');
  }

  // --- DETAIL SKILL PAGE ---
  async function renderDetailSkill(skill) {
    setText(document.querySelector('h2.w-dyn-bind-empty'), skill.Name);
    setHtml(document.querySelector('.w-dyn-bind-empty.w-richtext'), skill.Description || '');
  }

  // --- MAIN ---
  async function init() {
    const pageType = getPageType();
    if (!pageType) return;

    try {
      let products, companies, patents, skills, tags, productImages;

      if (['index', 'products', 'detail_product', 'detail_company'].includes(pageType)) {
        products = await fetchJSON('products.json');
      }
      if (['index', 'companies', 'detail_company', 'detail_product'].includes(pageType)) {
        companies = await fetchJSON('companies.json');
      }
      if (['patents', 'detail_patent', 'detail_company'].includes(pageType)) {
        patents = await fetchJSON('patents.json');
      }
      if (['index', 'detail_skill', 'detail_product'].includes(pageType)) {
        skills = await fetchJSON('skills.json');
      }
      if (pageType === 'detail_product') {
        productImages = await fetchJSON('product-images.json');
      }

      switch (pageType) {
        case 'index':
          await renderIndex({ products, companies, skills });
          break;
        case 'products':
          await renderProductsList(products);
          break;
        case 'companies':
          await renderCompaniesList(companies);
          break;
        case 'patents':
          await renderPatentsList(patents);
          break;
        case 'detail_product': {
          const slug = getSlug();
          const product = products.find(p => p.Slug === slug);
          if (product) await renderDetailProduct(product, companies, productImages, skills);
          break;
        }
        case 'detail_company': {
          const slug = getSlug();
          const company = companies.find(c => c.Slug === slug);
          if (company) await renderDetailCompany(company, products, patents);
          break;
        }
        case 'detail_patent': {
          const slug = getSlug();
          const patent = patents.find(p => p.Slug === slug);
          if (patent) await renderDetailPatent(patent);
          break;
        }
        case 'detail_skill': {
          const slug = getSlug();
          const skill = skills.find(s => s.Slug === slug);
          if (skill) await renderDetailSkill(skill);
          break;
        }
      }
    } catch (err) {
      console.warn('CMS Data Loader:', err.message);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
